package View;

import Model.Film;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author anasyalaili
 */
public class ViewHome extends javax.swing.JFrame {
    private ViewFilm viewFilm;
    private ViewHome viewHome;
    private Film[] dataFilm = new Film[100];
    private Film selectedFilm;
    int i = 0;    
    
    /**
     * Creates new form ViewHome
     */
    public ViewHome() {
        initComponents();   
        setLocationRelativeTo(null);
    }        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainHome = new javax.swing.JPanel();
        pnlTop = new javax.swing.JPanel();
        lblHeading = new javax.swing.JLabel();
        btnFilm1 = new javax.swing.JButton();
        btnFilm2 = new javax.swing.JButton();
        btnFilm3 = new javax.swing.JButton();
        btnFilm4 = new javax.swing.JButton();
        lblWhatsNow = new javax.swing.JLabel();
        pnlBottom = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMainHome.setBackground(new java.awt.Color(69, 69, 69));
        pnlMainHome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlMainHome.setPreferredSize(new java.awt.Dimension(900, 600));
        pnlMainHome.setSize(new java.awt.Dimension(900, 600));

        pnlTop.setBackground(new java.awt.Color(74, 99, 124));

        lblHeading.setFont(new java.awt.Font("Futura", 1, 36)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(255, 255, 255));
        lblHeading.setText("CINEMAXX");

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblHeading)
                .addContainerGap(650, Short.MAX_VALUE))
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(lblHeading)
                .addGap(30, 30, 30))
        );

        btnFilm1.setIcon(new javax.swing.ImageIcon("/Users/anasyalaili/Downloads/0_PosterPemlan/homeposter_endgame.jpg")); // NOI18N
        btnFilm1.setIconTextGap(0);
        btnFilm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilm1ActionPerformed(evt);
            }
        });

        btnFilm2.setIcon(new javax.swing.ImageIcon("/Users/anasyalaili/Downloads/0_PosterPemlan/homeposter_TTB.jpg")); // NOI18N
        btnFilm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilm2ActionPerformed(evt);
            }
        });

        btnFilm3.setIcon(new javax.swing.ImageIcon("/Users/anasyalaili/Downloads/0_PosterPemlan/homeposter_interstellar.jpg")); // NOI18N
        btnFilm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilm3ActionPerformed(evt);
            }
        });

        btnFilm4.setIcon(new javax.swing.ImageIcon("/Users/anasyalaili/NetBeansProjects/TicketingBioskop/homeposter_28yearslater.jpg")); // NOI18N
        btnFilm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilm4ActionPerformed(evt);
            }
        });

        lblWhatsNow.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblWhatsNow.setForeground(new java.awt.Color(255, 255, 255));
        lblWhatsNow.setText("Now Showing");

        pnlBottom.setBackground(new java.awt.Color(74, 99, 124));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ABOUT CINEMAXX");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FAQ");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CONTACT US");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MEMBERSHIP");

        javax.swing.GroupLayout pnlBottomLayout = new javax.swing.GroupLayout(pnlBottom);
        pnlBottom.setLayout(pnlBottomLayout);
        pnlBottomLayout.setHorizontalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBottomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(58, 58, 58)
                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(33, 33, 33))
        );
        pnlBottomLayout.setVerticalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMainHomeLayout = new javax.swing.GroupLayout(pnlMainHome);
        pnlMainHome.setLayout(pnlMainHomeLayout);
        pnlMainHomeLayout.setHorizontalGroup(
            pnlMainHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMainHomeLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pnlMainHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWhatsNow)
                    .addGroup(pnlMainHomeLayout.createSequentialGroup()
                        .addComponent(btnFilm1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFilm2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFilm3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFilm4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMainHomeLayout.setVerticalGroup(
            pnlMainHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainHomeLayout.createSequentialGroup()
                .addComponent(pnlTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lblWhatsNow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMainHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnFilm4, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFilm3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnFilm2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFilm1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(pnlBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlMainHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlMainHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void readFilmData() {
        try {
            try (BufferedReader reader = new BufferedReader(new FileReader("dataFilm.txt"))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    String[] parts = line.split(",");                    
                    if (parts.length >= 6) {
                        dataFilm[i] = new Film(parts[0], parts[1], parts[2], parts[3], parts[4], parts[5]);                        
                        i++;
                    }
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(viewHome, "Failed to load film data.");
        }
    }
    
    private void btnFilm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilm1ActionPerformed
        readFilmData();
        viewFilm = new ViewFilm(this, dataFilm[0]);
        ImageIcon icon1 = new ImageIcon(dataFilm[0].getPosterPath());                        
        this.setVisible(false);
        viewFilm.posterFilm.setIcon(icon1);        
        viewFilm.setVisible(true);
    }//GEN-LAST:event_btnFilm1ActionPerformed

    private void btnFilm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilm2ActionPerformed
        readFilmData();
        viewFilm = new ViewFilm(this, dataFilm[1]);                 
        ImageIcon icon2 = new ImageIcon(dataFilm[1].getPosterPath());        
        this.setVisible(false); 
        viewFilm.posterFilm.setIcon(icon2);        
        viewFilm.setVisible(true);
    }//GEN-LAST:event_btnFilm2ActionPerformed

    private void btnFilm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilm3ActionPerformed
        readFilmData();
        viewFilm = new ViewFilm(this, dataFilm[2]);
        ImageIcon icon3 = new ImageIcon(dataFilm[2].getPosterPath());        
        this.setVisible(false); 
        viewFilm.posterFilm.setIcon(icon3);        
        viewFilm.setVisible(true);
    }//GEN-LAST:event_btnFilm3ActionPerformed

    private void btnFilm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilm4ActionPerformed
        readFilmData();
        viewFilm = new ViewFilm(this, dataFilm[3]);
        ImageIcon icon4 = new ImageIcon(dataFilm[3].getPosterPath());        
        this.setVisible(false); 
        viewFilm.posterFilm.setIcon(icon4);        
        viewFilm.setVisible(true);
    }//GEN-LAST:event_btnFilm4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewHome().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFilm1;
    private javax.swing.JButton btnFilm2;
    private javax.swing.JButton btnFilm3;
    private javax.swing.JButton btnFilm4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblWhatsNow;
    private javax.swing.JPanel pnlBottom;
    public javax.swing.JPanel pnlMainHome;
    private javax.swing.JPanel pnlTop;
    // End of variables declaration//GEN-END:variables
}
